name: Terraform Apply

on: [push]

jobs:
  terraform_apply:
    environment: PIN-2
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TERRAFORM_VERSION: "0.12.15"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Terraform
      env:
        TERRAFORM_VERSION: "0.12.15"
      run: |
        tf_version=$TERRAFORM_VERSION
        wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
        unzip terraform_"$tf_version"_linux_amd64.zip
        sudo mv terraform /usr/local/bin/

    - name: Verify Terraform version
      run: terraform --version

    - name: Terraform init
      
      run: terraform init -input=false

    - name: Terraform validation
      run: terraform validate
    
    - name: terraform plan
      run: terraform plan
          
    - name: Terraform apply
      run: terraform apply -auto-approve -input=false
